# Generated by Django 3.2.11 on 2022-05-28 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='password1',
            new_name='password',
        ),
    ]
