# Generated by Django 3.2.11 on 2022-05-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_password1_account_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account',
        ),
    ]
